# Generated by Django 3.1 on 2020-11-08 01:54

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('id', models.CharField(db_index=True, default=shortuuid.main.ShortUUID.uuid, max_length=255, primary_key=True, serialize=False)),
                ('startdate', models.DateField(default=None, null=True)),
                ('enddate', models.DateField(default=None, null=True)),
                ('start_location', models.CharField(blank=True, max_length=64, null=True)),
                ('summary', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('classification', models.CharField(choices=[('work', 'Work'), ('pleasure', 'Pleasure'), ('both', 'Both')], max_length=35)),
            ],
        ),
    ]
