# Generated by Django 3.1 on 2020-11-14 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('id', models.CharField(db_index=True, default=shortuuid.main.ShortUUID.uuid, max_length=255, primary_key=True, serialize=False)),
                ('startdate', models.DateField(default=None, null=True)),
                ('enddate', models.DateField(default=None, null=True)),
                ('start_location', models.CharField(blank=True, max_length=64, null=True)),
                ('summary', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('classification', models.CharField(choices=[('work', 'Work'), ('pleasure', 'Pleasure'), ('both', 'Both')], max_length=35)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.CharField(db_index=True, default=shortuuid.main.ShortUUID.uuid, max_length=255, primary_key=True, serialize=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
